#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#



obj-$(CONFIG_TOUCHSCREEN_FTS_TB8504) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TB8504) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TB8504) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FTS_TB8504) += supported_ic/

